import adminRouter from './slice/admin.js';
import authRouter from './slice/auth.js';
import brandRouter from './slice/brand.js';
import cartRouter from './slice/cart.js';
import categoryRouter from './slice/category.js';
import chatRouter from './slice/chat.js';
import giftRouter from './slice/gift.js';
import messageRouter from './slice/message.js';
import notificationRouter from './slice/notifiaction.js';
import orderRouter from './slice/order.js';
import productRouter from './slice/product.js';
import profileRouter from './slice/profile.js';
import userRouter from './slice/user.js';
const router = (app) => {
    adminRouter(app);
    authRouter(app);
    brandRouter(app);
    cartRouter(app);
    categoryRouter(app);
    chatRouter(app);
    giftRouter(app);
    messageRouter(app);
    notificationRouter(app);
    orderRouter(app);
    productRouter(app);
    profileRouter(app);
    userRouter(app);
};
export default router;
